### ISSUE TITLE
Incompatibility with Jetbrains xcode-compat plugin

### ISSUE THREAD

**Issue by russhwolf** [touchlab/KotlinXcodeSync#7]
Jetbrains publishes the [xcode-compat](https://github.com/Kotlin/xcode-compat) plugin to ease some setup, including generating an Xcode project and auto-generating a `buildForXcode` gradle task. You can see it in-use in the AppCode new project templates.

This plugin conflicts with it because they both define an extension named "xcode". As far as I know this means it's impossible to use both on the same project.

**Comment by kpgalligan** [comment]
Hmm. Missed this. Seems like a simple change.

**Comment by kpgalligan** [comment]
Fixed in v0.2
